export const MESSAGES_GET = 'MESSAGES_GET';
export const MESSAGE_SEND = 'MESSAGE_SEND';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';

export const CONNECTION_CHANGED = 'CONNECTION_CHANGED';
export const PORT_CHANGED = 'PORT_CHANGED';
export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';
