export const MESSAGE_SEND_REQUEST = "MESSAGE_SEND_";
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
export const MESSAGE_SEND_FAILURE = "MESSAGE_SEND_FAILURE";

export const MESSAGES_GET_REQUEST = "MESSAGES_GET_REQUEST";
export const MESSAGES_GET_SUCCESS = "MESSAGES_GET_SUCCESS";
export const MESSAGES_GET_FAILURE = "MESSAGES_GET_FAILURE";
